# Generated by Django 3.2.6 on 2021-08-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20200722_0405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='season',
        ),
        migrations.DeleteModel(
            name='Season',
        ),
    ]
